### ISSUE TITLE
swift compiler error base on FBSDKShareKit (4.23.0)

### ISSUE THREAD

**Issue by qinweizhao** [facebook/facebook-sdk-swift#157] opened 2017-05-26 04:13 UTC
FacebookShare/LinkShareContent.swift

content.contentDescription = self.description
content.contentTitle = self.title
content.imageURL = self.imageURL

cannot assign to get-only property

**Comment by qinweizhao** [comment] 2017-05-26 04:15
I got the compiler error after update pods

**Comment by MrSilverstone** [comment] 2017-05-26 08:24
Same issue with CocoaPods 1.2.1 and xcode 8.3.2

**Comment by jxtmo** [comment] 2017-05-26 08:53
same issue!

**Comment by deepakbms** [comment] 2017-05-26 09:26
same issue, for now, i remove these lines

**Comment by sche** [comment] 2017-05-27 08:22
same issue

**Comment by sotozaki** [comment] 2017-05-27 08:22
save issue

**Comment by dangnguyenhuu** [comment] 2017-05-27 15:23
I facing same problem. Is there any solution?

**Comment by adrienyvon699** [comment] 2017-05-27 17:13
Hi, I confirm this issue too

**Comment by thaoth58** [comment] 2017-05-28 02:08
Seem like a lot of people face this issue :D

**Comment by 1amageek** [comment] 2017-05-28 05:32
same issue

**Comment by NikKovIos** [comment] 2017-05-28 13:39
The same

**Comment by taglia3** [comment] 2017-05-28 18:37
same issue

**Comment by phalladar** [comment] 2017-05-29 02:02
+1. Womp.

**Comment by dams2007** [comment] 2017-05-29 04:40
Same one too.

**Comment by happiehappie** [comment] 2017-05-29 14:48
+1

**Comment by eman6576** [comment] 2017-05-29 18:25
Same issue here.

**Comment by beautynanacalico** [comment] 2017-05-30 03:07
+1 [screenshot](https://karlstyner.s3.amazonaws.com/facebook_share_link_error.png)

**Comment by soulfoodz** [comment] 2017-05-30 04:29
Same issue

**Comment by aman-git** [comment] 2017-05-30 06:20
Compiler Error : 

content.contentDescription = self.description
content.contentTitle = self.title
content.imageURL = self.imageURL

Cocoa pods Version : 1.2.1
Xcode Version : Version 8.2.1 (8C1002)

Cannot assign to get-only property, attaching screenshot along
Whats the possible solution to this 

![screen shot 2017-05-30 at 11 49 49 am](https://cloud.githubusercontent.com/assets/17446818/26570425/2328f1ca-452e-11e7-9ccf-2ab1b838f439.png)

**Comment by mememto** [comment] 2017-05-30 07:34
Till the problem is solved i'm using:

    pod 'FacebookCore', '~> 0.2'
    pod 'FacebookLogin', '~> 0.2'
    pod 'FacebookShare', '~> 0.2'
    pod 'FBSDKCoreKit', '~> 4.22.1'
    pod 'FBSDKLoginKit', '~> 4.22.1'
    pod 'FBSDKShareKit', '~> 4.22.1'

**Comment by happiehappie** [comment] 2017-05-30 07:37
@mememto Is there a point to this? Since FacebookShare is just a swift wrap for FBSDKShareKit. Isn't this considered as a bad duplication?

**Comment by mememto** [comment] 2017-05-30 08:04
According to SDK documentation (https://developers.facebook.com/docs/swift/getting-started), you should add:
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
to install all the modules of the SDK. Taking into account that doing this, will install FBSDKCoreKit, FBSDKLoginKit & FBSDKShareKit with version 4.23.0 into your project, the only way i've found to install FacebookCore, FacebookLogin and FacebookShare with version 4.22.1 of FBSDKCoreKit, FBSDKLoginKit & FBSDKShareKit is this.
Not sure if this is a duplication or not. Just wanted to share my "temporary solution".

**Comment by NikKovIos** [comment] 2017-05-30 10:23
Solved using  pod 'Facebook-iOS-SDK', '~> 4.1' instead of all this swifty ..

**Comment by matvdg** [comment] 2017-05-31 13:16
same issue, temporary solved here: https://stackoverflow.com/questions/44248118/facebookshare-causing-compiler-error-after-update
Facebook, please UPDATE your changelog: last updated =  4.18.0 : 30 nov 2016 :$

**Comment by 1amageek** [comment] 2017-06-09 02:56
```
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
```

**Comment by ygbr** [comment] 2017-06-09 03:59
+1

**Comment by kasokuta** [comment] 2017-06-09 09:41
+1

**Comment by ygbr** [comment] 2017-06-09 15:55
There are 2 PR's with fixes for this bug (one is even CLA signed already), why not merge them and create a new release?

**Comment by tylermilner** [comment] 2017-06-10 23:48
I'm getting compiler errors after running `pod repo update` and then `pod install` as well. This seems like it's an easy fix. Please push a new release ASAP!

**Comment by mdilaveroglu** [comment] 2017-06-12 13:14
+1

**Comment by WowFactorMedia** [comment] 2017-06-12 13:58
+1

**Comment by szuniverse** [comment] 2017-06-14 08:38
+1

**Comment by Jur4s** [comment] 2017-06-15 12:35
+1

**Comment by bartoszhernas** [comment] 2017-06-17 01:27
+1

**Comment by Sweefties** [comment] 2017-06-21 14:27
+1

**Comment by Sweetog** [comment] 2017-06-22 04:08
+1
Not sure using 
`pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'`
is a good idea, not that @1amageek would delete his repo but @1amageek did that. Seems the best answer until fixed is in Podfile:

```
pod 'FacebookCore', '~> 0.2'
pod 'FacebookLogin', '~> 0.2'
pod 'FacebookShare', '~> 0.2'
pod 'FBSDKCoreKit', '~> 4.22.1'
pod 'FBSDKLoginKit', '~> 4.22.1'
pod 'FBSDKShareKit', '~> 4.22.1'
```
@mememto it is not duplication but is version specificity and I think you figured that out, FacebookCore, FacebookLogin and FacebookShare will install the FBSDK libs

**Comment by rollr76518** [comment] 2017-06-22 05:48
still have problem and 
Using FBSDKCoreKit (4.23.0)
Using FBSDKLoginKit (4.23.0)
Using FBSDKShareKit (4.23.0)
Using FacebookCore (0.2.0)
Using FacebookLogin (0.2.0)
Using FacebookShare (0.2.0)

**Comment by nemexyz** [comment] 2017-06-27 14:36
+1

**Comment by denistrofimov** [comment] 2017-06-28 09:14
+1

**Comment by kudo69** [comment] 2017-06-29 05:48
+1

**Comment by ercillagorka** [comment] 2017-07-03 07:39
+1

**Comment by jay-citrin** [comment] 2017-07-05 07:18
+1

**Comment by EvsenevDev** [comment] 2017-07-06 05:23
same issue :(

**Comment by ericmarkmartin** [comment] 2017-07-07 21:08
+1

**Comment by adriansoghoian** [comment] 2017-07-07 21:09
+1

**Comment by RaymondBakker** [comment] 2017-07-07 21:53
Hey FB devs, do you even test your libraries before you push new versions? This is ridiculous.

**Comment by ericmarkmartin** [comment] 2017-07-07 22:15
It's not like it's a change that needs any level of testing or anything either. I've literally been commenting out the 3 lines the OP mentioned every time I run `pod install` and it works perfectly.

**Comment by storyhe** [comment] 2017-07-10 07:34
+1

**Comment by Jakkawad** [comment] 2017-07-10 13:13
+1

**Comment by akbashev** [comment] 2017-07-10 14:42
+1

**Comment by FrancisZamora** [comment] 2017-07-11 01:34
+1

**Comment by oboupo** [comment] 2017-07-12 21:17
+1

**Comment by MasterBozzo** [comment] 2017-07-13 07:32
Unlock and comment like that .

extension LinkShareContent: SDKBridgedContent {
  internal var sdkSharingContentRepresentation: FBSDKSharingContent {
    let content = FBSDKShareLinkContent()
    //content.contentDescription = self.description
    //content.contentTitle = self.title
    //content.imageURL = self.imageURL
    content.quote = self.quote
    content.contentURL = self.url
    content.hashtag = self.hashtag?.sdkHashtagRepresentation
    content.peopleIDs = self.taggedPeopleIds
    content.placeID = self.placeId
    content.ref = self.referer
    return content
  }
}

**Comment by Jur4s** [comment] 2017-07-13 07:43
@MasterBozzo That's what I did for the moment, but I don't understand how Facebook don't react and correct this error. Impossible to use carthage any more with this library :( Modify the pod source file isn't the right things to do :/

**Comment by rajeevwhiz** [comment] 2017-07-16 18:34
+1

**Comment by mohsinka** [comment] 2017-07-19 08:04
+1. Yeah! Still the same.

**Comment by taminif** [comment] 2017-07-19 08:05
same issue!

**Comment by andrea689** [comment] 2017-07-21 08:54
+1

**Comment by oskarko** [comment] 2017-07-25 09:46
Same here +1

**Comment by caroline-davis** [comment] 2017-08-01 08:52
+1

**Comment by GhaisB** [comment] 2017-08-01 09:00
+1

**Comment by klyngov** [comment] 2017-08-01 20:57
+1

**Comment by isairuiz** [comment] 2017-08-02 01:04
+1

**Comment by johntiror** [comment] 2017-08-02 18:19
+1

**Comment by diegotrevisan** [comment] 2017-08-03 12:12
+1

**Comment by shingsoso** [comment] 2017-08-08 09:24
same :) 
waiting for update
;D

**Comment by Zulqarnain-Mustafa** [comment] 2017-08-09 11:20
facing same issue.

**Comment by NMKRebelute** [comment] 2017-08-11 13:20
Still..

Installing FBSDKCoreKit (4.25.0)
Installing FBSDKLoginKit (4.25.0)
Installing FBSDKShareKit (4.25.0)
Installing FacebookCore (0.2.0)
Installing FacebookLogin (0.2.0)
Installing FacebookShare (0.2.0)

Dear Facebook team please resolve the problem.

**Comment by goufo** [comment] 2017-08-12 14:10
+1

**Comment by ismoli** [comment] 2017-08-14 12:50
I like how quickly FB react to this 🥇

**Comment by diegotrevisan** [comment] 2017-08-14 17:55
After all, who needs facebook nowadays? /ironic

**Comment by cbarbera80** [comment] 2017-08-15 10:56
ridiculous!

**Comment by tylermilner** [comment] 2017-08-15 23:16
I don't know about you guys, but I gave up on Facebook ever fixing this and went back to the Obj-C SDK. Sure, I had to deal with a lovely implicitly unwrapped optional crash during Apple review, but at least my project compiles when using the latest Facebook SDK. ¯\_(ツ)_/¯

**Comment by mingflifb** [comment] 2017-08-20 17:45
Graph API 2.9 introduced a 90-day breaking change that prohibited the overriding of these parameters. See https://developers.facebook.com/docs/apps/changelog#v2_9

**Comment by dmr07** [comment] 2017-08-26 19:40
+1

**Comment by CoffeePowered** [comment] 2017-08-31 18:53
What in the world are these FB guys doing? This must be some kind of prank that ended up in production, for over **3 months** now. Get real, Facebook!

**Comment by nemexyz** [comment] 2017-09-01 15:08
The library is obsolete. @1amageek try to make the arrangement but the rules of Facebook will not let him, then who keeps the repository? it is ridiculous what happens here if many developers take Facebook Swift for their projects. Better get on with ObjC. #159

**Comment by denirorobert** [comment] 2017-09-12 22:02
still exists ☹️

**Comment by vatsal1992** [comment] 2017-09-23 07:51
FB guys..! what are you doing.. come on guys  you must fix this issue.

**Comment by francodriansetti** [comment] 2017-09-26 14:33
+1

**Comment by francodriansetti** [comment] 2017-09-26 15:37
+1

**Comment by kevni111** [comment] 2017-10-01 09:22
+1

**Comment by zhihuitang** [comment] 2017-10-02 11:12
Seems our the great company Facebook doesn't care about it at all

**Comment by adnanboz** [comment] 2017-10-02 18:30
+1

**Comment by cs14rendra** [comment] 2017-10-05 21:22
I am using these Pod and its working fine . 
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

tested on xode 8 and xcode 9
(i got it from a tutorials, i will update link later)

**Comment by aarkus7** [comment] 2017-10-06 20:48
+1

**Comment by SGBRocks73** [comment] 2017-10-11 03:13
<img width="719" alt="screen shot 2017-10-11 at 14 06 56" src="https://user-images.githubusercontent.com/22512474/31420494-9addcc04-ae8d-11e7-856f-6b587e407308.png">

Those fields have been deprecated in 4.22.0 (18 Apr 2017). I would recommend just comment out.

**Comment by gfosco** [comment] 2017-10-12 00:34
4.27.1 of the obj-c SDK is out, 0.3.0 of Swift sdk is out.  All of this should be resolved.

**Closed by gfosco** 2017-10-12 00:34 UTC

**Comment by atistank** [comment] 2017-11-08 14:14
4.27.1 same problem :( they don't fix it

**Comment by ZhixiangWangCR7** [comment] 2018-08-08 06:29
+1

**Comment by memedinaa** [comment] 2018-12-12 06:06
Installing FBSDKCoreKit (4.38.1)
Installing FBSDKLoginKit (4.38.1)
Installing FBSDKShareKit (4.38.1)
Installing FacebookCore (0.5.0)
Installing FacebookLogin (0.5.0)
Installing FacebookShare (0.5.0)
