### ISSUE TITLE
Not working Swift 3.0.1 using pods

### ISSUE THREAD

**Issue by Dylan-Erskine** [facebook/facebook-sdk-swift#104] opened 2016-11-19 02:27 UTC
When I try to add it using pods I get the error "Convert to current Swift syntax", 

more info and images [http://stackoverflow.com/questions/40688433/facebook-sdk-not-working-swift-3](url)

**Comment by AnthonyWhitakerJr** [comment] 2016-11-23 19:57
Duplicate of issue #98.

**Closed** 2017-10-12 00:36 UTC
