### ISSUE TITLE
CocoaPods Install Not Working

### ISSUE THREAD

**Issue by oliviabrown9** [facebook/facebook-sdk-swift#10] opened 2016-07-14 23:01 UTC
Every time I try to install through CocoaPods, I get the following error:
`[!] Unable to find a specification for `FacebookCore``

I'm able to install other (not Facebook) pods through CocoaPods, so that's not the issue.

**Comment by johninla** [comment] 2016-07-14 23:03
The code snippet Facebook provides is lacking the `'` around the pod names. So, your Podfile should look like:

`use_frameworks!
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'`

**Comment by oliviabrown9** [comment] 2016-07-14 23:13
Here's the current code in my Podfile, and the install isn't working.

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HoldMeAccountable' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoldMeAccountable
	
	pod 'FacebookCore'

	pod 'FacebookLogin'

	pod 'FacebookShare'
end
```

**Comment by nlutsenko** [comment] 2016-07-14 23:17
Nice catch. Sending a fix in few brief moments.

**Comment by nlutsenko** [comment] 2016-07-14 23:18
And it should be fixed now. Thanks again for catching this.

**Closed by nlutsenko** 2016-07-14 23:18 UTC
Labels: documentation

**Comment by nlutsenko** [comment] 2016-07-14 23:53
@oliviabrown9, sorry, missed your comment.
Could you run `pod repo update` before running `pod install`?
The inability to find the pods can be caused by outdated local checkout of cocoa pods spec repo.

**Comment by oliviabrown9** [comment] 2016-07-15 00:05
Thank you! Updating fixed it! Sorry for the simple error on my part!

**Comment by nlutsenko** [comment] 2016-07-15 00:05
Absolutely fine, happy to help!
