### ISSUE TITLE
Xcode 8.3 Swift 3.1 fails to compile application due to FacebookCore

### ISSUE THREAD

**Issue by rahimizad** [facebook/facebook-sdk-swift#131] opened 2017-02-03 18:18 UTC
Showing All Messages
Command failed due to signal: Segmentation fault: 11

`
1.	While loading members for 'PictureView' in module 'FacebookCore'
2.	While deserializing PatternBindingDecl #83in 'FacebookCore'
3.	While deserializing 'pictureAspectRatio' (VarDecl #84)in 'FacebookCore'
4.	While deserializing decl #142 (XREF)in 'FacebookCore'
5.	Cross-reference to module 'FacebookCore'
	... UserProfile
	... in an extension in module 'FacebookCore'
	... PictureAspectRatio
6.	While loading members for extension of UserProfile in module 'FacebookCore'
7.	While deserializing 'Completion' (TypeAliasDecl #97)in 'FacebookCore'
8.	While deserializing decl #178 (XREF)in 'FacebookCore'
9.	Cross-reference to module 'FacebookCore'
	... UserProfile
	... in an extension in module 'FacebookCore'
	... FetchResult
10.	While loading members for extension of UserProfile in module 'FacebookCore'
11.	While deserializing 'loadCurrent' (FuncDecl #105)in 'FacebookCore'
`

**Comment by oiledCode** [comment] 2017-02-06 12:17
Same issue in my project

**Comment by distantnative** [comment] 2017-02-06 15:46
Here as well

**Comment by magin** [comment] 2017-02-06 22:25
Same issue

**Comment by barbarosd** [comment] 2017-02-09 09:33
same issue !!

**Comment by eddie1707** [comment] 2017-02-13 13:07
Same here!

**Comment by sohamgarud** [comment] 2017-02-14 04:04
Same here

**Comment by mikeknapp** [comment] 2017-02-19 09:27
Same here.... any solutions? Everything was working fine. Then I upgraded to Sierra on a fresh OS install. Reinstalled the Pods and got this error.

**Comment by mikeknapp** [comment] 2017-02-20 02:58
I solved this by downgrading to [Xcode 8.2.1](https://developer.apple.com/download/more/) (released Dec 19, 2016).

It has possibly been caused by an interaction between the new versions of FBSDKCoreKit and FBSDKLoginKit (4.19.0) -- or even just the FB SDK as a whole -- and the new Xcode somehow.

**Comment by ckalbas** [comment] 2017-02-21 01:46
But we can't run iOS Beta 10.3 on Xcode 8.2.1

**Comment by exocode** [comment] 2017-03-14 11:03
any news on that? I am quite new to carthage, but none of the facebook repos would compile. So maybe I am doing something wrong?

My Cartfile

`github "facebook/Facebook-SDK-Swift"`

also tried 

`facebook/facebook-ios-sdk`

The compilation:
```

➜  carthage git:(master) ✗ xcodebuild -version
Xcode 8.3
Build version 8W143q
➜  carthage git:(master) ✗ carthage version
0.20.1


➜  carthage git:(master) ✗ carthage update
*** Fetching Facebook-SDK-Swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Downloading facebook-ios-sdk.framework binary at "4.20.1"
*** Checking out facebook-ios-sdk at "sdk-version-4.20.1"
*** Checking out Facebook-SDK-Swift at "0.2.0"
*** xcodebuild output can be found in /var/folders/kt/t6w8hz2j53s39ktnvmqhyzh00000gn/T/carthage-xcodebuild.iLAn5g.log
*** Building scheme "Bolts-macOS" in Bolts.xcodeproj
*** Building scheme "Bolts-tvOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-watchOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/jan/iOS/carthage/carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKCoreKit-Dynamic -configuration Release -derivedDataPath /Users/jan/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.20.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/kt/t6w8hz2j53s39ktnvmqhyzh00000gn/T/carthage-xcodebuild.iLAn5g.log

```

here is a GIST of the output

https://gist.github.com/exocode/e4418b5fa5a2d8ff5b3e857088b57fe5

**Comment by ffittschen** [comment] 2017-03-27 20:28
The cause of this issues seems to be fixed in https://github.com/facebook/facebook-ios-sdk/pull/853.

**Comment by LiborZ** [comment] 2017-03-28 20:18
Please fix this. Thanks

**Comment by yakisama12** [comment] 2017-03-29 09:41
Xcode 8.3 Swift 3.1 is officially released and the issue still remains

**Comment by PushpakN** [comment] 2017-03-29 21:03
Not able to use Xcode 8.3(Swift 3.1) for my project due to this issue. Please fix this.

**Comment by adomanico** [comment] 2017-03-29 21:14
Workaround until someone from Facebook responds: you can fork my branch and target the fork in Carthage

https://github.com/facebook/facebook-ios-sdk/pull/853

**Comment by anfriis** [comment] 2017-03-30 09:55
Having the same issue as @PushpakN.

If you guys want a temporary fix, I can recommend this fork:
https://github.com/mylifeasdog/facebook-sdk-swift

It works fine for me!

**Comment by neptis-mobile** [comment] 2017-03-30 12:00
Same here!

**Comment by PushpakN** [comment] 2017-03-30 12:50
@anfriis no success, still getting error Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/.../Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKCoreKit-Dynamic -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.20.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/t0/kq0kpr8j4710hvs8m1_wk5p582_w2_/T/carthage-xcodebuild.y0WjgS.log

**Comment by ckalbas** [comment] 2017-03-30 13:39
After the official Xcode 8.3 release and pod updating my project, it worked.

**Comment by jmballantyne** [comment] 2017-03-30 13:52
no success here. still getting the same build fail error 65

**Comment by netadapt** [comment] 2017-03-30 14:09
@PushpakN Update your Cartfile to : 

github "mylifeasdog/facebook-sdk-swift" "master"

After stepping back to 8.2 for a successful build, I was then unable to test on updated 10.3 phones, and needed a solution.  So, glad to have this fork to work with for now.

**Comment by PushpakN** [comment] 2017-03-30 18:51
Use pods or Carthage (github "mylifeasdog/facebook-sdk-swift" "master") to build successfully. @netadapt  thanks :)

**Comment by fostah** [comment] 2017-03-31 14:23
I'm seeing the same issue with Carthage and facebook-ios-sdk. When you dig in, the error is:
```
error: redefinition of module 'FBSDKCoreKit'
framework module FBSDKCoreKit {
                 ^
/Users/tdeane/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.20.1/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/module.modulemap:1:18: note: previously defined here
framework module FBSDKCoreKit {
                 ^
1 error generated.
```

**Comment by zirinisp** [comment] 2017-04-02 01:09
I am getting the same issue. I had the same error in another framework and had to change compiler optimisations to make it work. I will try the fork given.

**Comment by applehawk** [comment] 2017-04-05 10:41
Same issue

**Comment by fostah** [comment] 2017-04-06 12:34
In case you're only watching this issue, 4.21.0 seems to address this now, as of yesterday:

https://github.com/facebook/facebook-ios-sdk/pull/853

**Comment by nlutsenko** [comment] 2017-04-08 23:52
Hey everyone,

Sorry for being silent all this time.
Yes, indeed there was a change needed to the Facebook ObjC SDK, that we depend on here from Swift.
I am currently working on updating all small tidbits and intricacies here, as well as adding long-awaited features to the Swift SDK.

The release for 0.3 Swift SDK is coming very soon, so stay tuned.

**Comment by WassimSDE** [comment] 2017-04-14 15:40
Any update ?

**Comment by jordimares** [comment] 2017-04-14 21:50
I am waiting for this too. This is blocking me to continue the development of an app of which I need a demo ready in two weeks...

**Comment by exocode** [comment] 2017-04-15 01:17
@jordimares I've done it in the meanwhile by cocoapods. If it's only for "demo" simple try the pod approach

**Comment by sarthakappinventiv** [comment] 2017-04-25 06:14
Hi I'm facing the same issue in the xCode version 8.3.2.

**Comment by sameh0** [comment] 2017-04-26 20:15
the issue is still persistent in Xcode 8.3.2

**Comment by sanjaysurpleplay** [comment] 2017-05-04 12:14
Hi  xcode 8.3.2 with swift 3.1 facebook login not working.

**Closed** 2017-10-12 00:36 UTC
